
def get_ignored_elements():
    """
        # Lista de classes, IDs e seletores a serem ignorados na raspagem das noticias
        Website onde estão sendo ignorando os elementos.
        - www.metropoles.com
        - g1.globo.com
        - dinheirama.com
        - valor.globo.com
        - www.terra.com.br
        - www.viomundo.com.br
        - sputniknewsbr.com.br
        - www.bbc.com
        - www.infomoney.com.br
    """
    ignored_elements = [
        ".kGDZUR.styles__Head-sc-20qlq5-1",
        ".kKHBpG.FooterWrapper-sc-126uqta-0",
        ".rs_skip.comments.fMHRul.NoticiaComentariosWrapper-sc-f60as3-0",
        ".dcgszM.NoticiaInternaWrapper__Large-sc-481g5p-6 > .bnt-share.cVXtoZ.Buttons__Button-sc-brbebv-0",
        ".bNbeoR.WidgetMaisLidasWrapper-sc-qh5njc-0",
        ".kxKaMq.TagsNoticiaWrapper-sc-pr4a71-0",
        ".m-bold",
        ".m-related-news.m-news-list-content",
        "#m-newsletter",
        ".dZHAKd.Grid__Col-sc-owmjhw-2",
        ".imyXFN.NoticiaInternaWrapper__ImagemDestaque-sc-481g5p-4",
        ".kuXdhW.Grid__Col-sc-owmjhw-2 > .gfliFc.NoticiaInternaWrapper__SocialMedias-sc-481g5p-7 > .pDKOJ.style__ShareSocialMediaWrapper-sc-f4hti2-0",
        "footer",
        ".bastian-page",
        ".unmute-modal",
        "#c79",
        ".mc-bottom",
        ".mc-column-mais-lidas.mc-column",
        ".entities.mc-column",
        ".glb-topo",
        ".glb-share-bar_icons",
        "#chunk-1b0pm > .active-extra-styles.content-text.mc-column > .content-text__container > [href] > em",
        ".comments.mc-column",
        ".shadow-video-flow",
        ".has-next-article-sticky.mc-column",
        "#chunk-7vrel > .active-extra-styles.content-text.mc-column > .content-text__container",
        ".elementor-55811.elementor",
        ".no-shadow.normal.main-builder-header.penci-header-builder.penci_header",
        ".ads1a",
        ".tradingview-widget-container",
        ".single-breadcrumb.penci-breadcrumb.container",
        "span:nth-of-type(3)",
        ".pc-hasel.pcmiddle-normal.penci-sticky-mid.penci-desktop-sticky-mid > .container-1400.container",
        ".bioimg-round.abio-style-1.post-author",
        ".penci-posts-related-grid.post-related",
        ".dinhe-sidebar-ads",
        ".pcicon-right.pciconp-right.pcalign-center.style-1.penci-sidebar-content.penci-sidebar-right",
        ".dinhe-meio-do-post-ads",
        ".anuncio3",
        ".post-tags",
        ".hide-like-count.post-share.social-align-default.tags-share-box-2_3.tags-share-box-s2.single-post-share.tags-share-box-top.tags-share-box.sstyle-",
        ".penci-featured-caption",
        ".custom-footer-edg--middle",
        ".custom-footer-edg--lock.custom-footer-edg--top--wrapper",
        ".related-videos-no-margin.bg-color-noticias.related-videos",
        ".article__header",
        ".zaz-app-t360-navbar",
        ".breadcrumb",
        ".bg-color-noticias.article__header__content__background--right.article__header__content__background",
        ".bg-color-noticias.article__header__content__background--left.article__header__content__background",
        ".article__header__info__comments > [href]",
        ".related-news",
        ".color-noticias.article__content--newsletter",
        ".app-t360-home-table.t360-related-content",
        ".footer",
        ".ad-varejo-container",
        ".fb_iframe_widget_fluid_desktop.fb_iframe_widget.fb-comments",
        "#app-t360-sva-bar",
        "div.table-range-flex.t360-related-content:nth-of-type(7)",
        "div.table-range-flex.t360-related-content:nth-of-type(3)",
        "div.table-range-flex.t360-related-content:nth-of-type(6)",
        "div.table-range-flex.t360-related-content:nth-of-type(5)",
        ".article__content--right",
        "#article-sign-notifications-container",
        ".article__content--internal.article__content--credit",
        ".t360-tags",
        ".article__content--left > .t360-sharebar__wrapper > .t360-sharebar",
        ".article__content--left > .t360-sharebar__wrapper",
        "footer.py-5 > .container",
        ".submenu.offcanvas-start.offcanvas",
        ".py-3",
        ".mx-auto.tag-active",
        ".align-items-center.mx-auto.navbar-nav",
        ".my-4.text-center > .addtoany_shortcode",
        ".text-start.figure-caption",
        "p:nth-of-type(1)",
        ".code-block-2.code-block",
        "div.align-items-center.d-md-block.d-flex.post.col:nth-of-type(3)",
        "#comentario > .container",
        "section.pb-5:nth-of-type(4)",
        ".my-4.text-start",
        ".m-active.endless__item > .m-content.container > .layout > .sidebar",
        ".m-active.endless__item",
        ".footer",
        ".sidebar",
        ".article__footer",
        ".anchor",
        ".bbc-tpioxw",
        ".bbc-1pg0aej",
        ".e5jcirq1.bbc-1l5nxv5",
        ".bbc-1lgjp5v",
        ".e10yv9r12.bbc-15h3qrt.ep1mqcj0",
        ".bbc-l2kb15",
        "header",
        ".e1rfboeq7.bbc-4quw3x",
        "#siteFooter",
        "div.my-6.md\:px-0.px-6:nth-of-type(6)",
        "div.my-6.md\:px-0.px-6 > .mx-auto.max-w-2xl",
        ".cta-middle",
        ".w-full.bg-wl-neutral-950.antialiased.font-im-sans",
        ".max-w-\[280px\].w-full.justify-between.flex.relative",
        ".content-text__container",
        ".active-extra-styles.content-text.mc-column",
        ".chunk-ctp7d",
        ".mais-lidas__wrapper",
        ".mais-lidas.mais-lidas",
        ".mc-column-mais-lidas.mc-column",
        ".theme-border-color-primary.feed",
        ".mc-bottom",
        ".content-media__description",
        ".content-media__container.mc-column",
        ".content-photo.content-media.medium-uncollapsed.row",
        ".chunk-f6sok",
        "div.mc-column:nth-of-type(3)",
        ".shadow-video-flow",
        ".has-text-align-center",
    ]
    return ignored_elements